### ISSUE TITLE
Infinity - Issue 5 Delete Config File

### ISSUE THREAD

**Issue by Rixxaw** [kristi71111/ModPack-issues-and-fixes#1]
Your fix for Issue 5 doesn't work.  You can delete the Forestry config file all you want and the FTB launcher just over-writes it.

Why is it hard for them to just issue the fix?  I documented the changes in the config file between the versions on their forums.  They have since released 2 versions that are still broken.

**Comment by kristi71111** [comment]
Hmm are you doing this correctly?? I'l edit the fix to be in full detail. However I do agree that lately I honestly dont know what they are doing. I've been having more and more issues eatch release :/

**Comment by kristi71111** [comment]
Closing the issue. Thanks for informing me.
